Readme 1
lyh951212/git_team_final pull request #8
Opened 2022-10-28 06:05 UTC by lyh951212

## 작업 개요 (이슈 번호)
이슈번호 #2
프로젝트에 대한 간단한 요약을 남김

## 작업 내용 (변경 사항)
프로젝트에 대한 간단한 요약을 남김

## 리뷰 요청 사항
주제에 맞게 남겼는지 확인해주세요

2022-10-28 06:13 UTC, lyh951212 reviewed
잘 썼음

2022-10-28 06:15 UTC, seulchan approved these changes

2022-10-28 06:17 UTC, moon-July5 approved these changes

2022-10-28 06:19 UTC, seulchan requested changes
pull request 제목 변경 바람

2022-10-28 06:31 UTC, seulchan approved these changes

2022-10-28 06:32 UTC, seulchan commented
굿굿굿

2022-11-01 04:27 UTC, soonduck approved these changes

2022-11-01 05:47 UTC, merged